<?php

function notify($to, $data)
{

    //$api_key = "AAAAKHMlqeU:APA91bFAbmwf0rVrcc7ylVA7H85WHFZTLaYd-d-qCIqs2xQfS0fvQsgLcV-mrzNbU2Bd_VRuk4-snxJfjXWtKeTzfSNEfwowbmBlq8uOLOkrX-ueovhkMTrMOFwCoYIWpFCGkC3vOXvg"; //Test Project
    $api_key = "AAAAldiccAc:APA91bHVAy127bLeKz5ht2mfElSR7Lxr6HvrKESyTHYns9ijvAeqRkWMs_RZsLpD3STYd-IJNbpvEBSDR4q9bBV-iLIPfzHO3V6qW4ZCS8Ha4Q7-niPka4DzSocjz-HrQzE8LASnwWoq"; //Examen Project
    $url = "https://fcm.googleapis.com/fcm/send";
    $fields = json_encode(array('to' => $to, 'notification' => $data));

    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, ($fields));

    $headers = array();
    $headers[] = 'Authorization: key =' . $api_key;
    $headers[] = 'Content-Type: application/json';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);
}

$title = $_POST['title_n'];
$message = $_POST['message_n'];

//$to = "c3PTdXqfQ6aZDbO8YdUWmF:APA91bF_KupHj1t96YQ79Yly00vxCymu4Yu_X1sigZ_m3mb3LaLq5MgvVFl0pvkB_W3YivxxBdP4dBGxrDU9bmju3PqUBlIgxs8f-t1QJaiJRV5Nlzp983OQYZ0xV2MgfHZcFXuBS7i0"; //Test Device
$to = "crl7DQntSq6HgekxuHssgP:APA91bF_d3aVlXRgDWIEGTFFznspssusO5mdigj4rFPRT4nSVxghOV8oxzD5EtD10gxcD1ITI6lg29WpBHXrzWQH-Eaf9OnKJETtPdIcsNGkK3CAvTDr1ZSKZ0CYOYR2OqODi4bO5bYq"; //Examen Device
$data = array(
    'title' => $title,
    'body' => $message,
);


notify($to, $data);
echo "Enviando notificacion...<br><br>";
echo "INTEGRANTES:<br>";
echo "Valeria Nicoll Calderon Rodriguez<br>";
echo "Diego Joel Flores Camargo<br>";
